[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "dictol"
version = "0.1.1"
description = "A dictionary learning package for classification"
readme = "README.md"
requires-python = ">=3.11"
license = { text = "MIT" }
authors = [
    { name = "Tiep Vu", email = "vuhuutiep@gmail.com" }
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"
]

dependencies = [
    "numpy>=1.17.4",
    "scipy>=1.4.1"
]

[project.urls]
Homepage = "https://github.com/tiepvupsu/dictol_python"

[tool.setuptools]
packages = ["dictol"]
package-dir = { "dictol" = "dictol" }
include-package-data = true
